"""agrege tabla tareas

Revision ID: 2040ea30abf6
Revises: e7997fcfc095
Create Date: 2023-03-15 15:51:08.552095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2040ea30abf6'
down_revision = 'e7997fcfc095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_de_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'RELIZANDOSE', 'REALIZADA', 'CANCELADA', name='estadotareaenum'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    # ### end Alembic commands ###
