# Generated by Django 4.1.7 on 2023-03-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorias',
            new_name='Categoria',
        ),
    ]
